package com.drbrosdev.extractor.data.extraction.relation

import androidx.room.Embedded
import androidx.room.Relation
import com.drbrosdev.extractor.data.extraction.record.LupaImageMetadataRecord
import com.drbrosdev.extractor.data.extraction.record.UserEmbeddingRecord

/**
 * Extraction data generated by the user.
 */
data class UserExtractionRelation(
    @Embedded val lupaImageMetadataRecord: LupaImageMetadataRecord,

    @Relation(
        parentColumn = "media_store_id",
        entityColumn = "lupa_image_id"
    )
    val userEmbedEntity: UserEmbeddingRecord
)
